### ISSUE TITLE
Implement checks for duplicate synynoms

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamxpathvalidator#1]
Copied from https://github.com/edamontology/edamontology/issues/170, which was in the wrong project.

@hmenager can you add checks that synonyms are unique, all types:
hasExactSynonym 
hasNarrowSynonym
hasBroadSynonym

this will ensure we catch errors, e.g. https://github.com/edamontology/edamontology/issues/131

Another comment from @joncison : This of course should be namespace aware.

**Comment by matuskalas** [comment]
The sub-ontology awareness may however be somewhat risky business with respect to text mining, but that's something that expert text mining practitioners should advise us on.

From a purely logical and linguistic perspective, the sub-ontology awareness makes a good sense (_i.e._ allowing same synonyms between sub-ontologies; although perhaps not for exact synonyms). But a similarly good logical/linguistic sense makes keeping duplicate and multiplicate synonyms even within one sub-ontology.

also `hasRelatedSynonym`?

**Comment by matuskalas** [comment]
For further discussion about what should actually be done with duplicate/multiplicate synonyms beyond finding them (allow or not; between sub-ontologies or within; exact or which synonyms), please refer to https://github.com/edamontology/edamontology/issues/233.

**Comment by matuskalas** [comment]
This should also apply to:
hasRelatedSynonym
relatedTerm

**Comment by joncison** [comment]
Closing this ... duplicated synonyms will be detected by use of ROBOT report, see https://github.com/edamontology/edamverify
