### ISSUE TITLE
Add synonyms versus primary labels check (case insensitive)

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamxpathvalidator#3]
Please add into the the synonyms multiplicity check:

* Primary labels

* Case-insensitivity

To avoid issues as https://github.com/edamontology/edamontology/issues/244 and https://github.com/edamontology/edamontology/issues/130

**Comment by joncison** [comment]
giving this a nudge @hmenager

**Comment by joncison** [comment]
giving this another nudge @hmenager - see https://github.com/edamontology/edamontology/issues/244

good to get this in place

**Comment by joncison** [comment]
This will be handled via use of ROBOT report, see https://github.com/edamontology/edamverify
