### ISSUE TITLE
Don't understand this error message

### ISSUE THREAD

**Issue by joncison** [edamontology/edamxpathvalidator#5]
```
multiple concepts with the same namespace  have the same synonym 'Small molecule sketch' - 'Chemical structure image' (http://edamontology.org/data_1712) -> 'Chemical structure image' (http://edamontology.org/data_1712)
```

There's only concept listed so this doesn't compute :).  

"Small molecular sketch" was a synonym in the (now-deprecated) *Chemical structure sketch* - which is replacdd by *Chemical structure image*, if that helps .

I could be missing something ...

**Comment by hmenager** [comment]
did you modify something on this @joncison ? the error doesn't seem to be there anymore...

**Comment by joncison** [comment]
yeah ... I'm fairly sure I fixed this one (a while ago)
